[package]
name = 'UseCases'
version = '1.0.0'

[dependencies]
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../../aptos-core/aptos-move/framework/aptos-token" }
AptosTokenObjects = { local = "../../../aptos-core/aptos-move/framework/aptos-token-objects" }
Agent = { local = "../agent" }

[addresses]
use_cases = "0x007"